# Use an official NVIDIA CUDA runtime as a parent image
FROM nvidia/cuda:12.4.0-runtime-ubuntu22.04

# Install Python
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-cffi \
    ibglib2.0-0 \
    libgl1-mesa-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /app
COPY ./fastapi-backend/requirements.txt .

RUN ls


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install onnxruntime-gpu==1.19.*

COPY ./vector-database /vectordb
COPY ./fastapi-backend/ .

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME=FastAPI

# Run app.py when the container launches
CMD ["fastapi", "run", "main.py", "--port", "8000"]